name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.5.4+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluttertoast: ^3.1.3
  path_provider: ^1.3.0
  video_player: ^0.10.2+1
  image_picker_saver: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/image/sol.svg
   - assets/image/header2.png
   - assets/image/back.png
   - assets/image/buahApel.png
   - assets/image/embuntep.jpg
   - assets/image/tumap.png
   - assets/image/logoC.png
   - assets/image/logoB.png
   - assets/image/caption.png
   - assets/image/pupuk.png
   - assets/icon/Hscab.png
   - assets/icon/Hbitrot.png
   - assets/icon/Hbusap.png
   - assets/icon/Hcedar.png
   - assets/icon/Hemtep.png
   - assets/icon/Hberda.png
   - assets/icon/Hbusar.png
   - assets/icon/Hblarot.png
   - assets/icon/Hkekel.png
   - assets/icon/Hkuda.png
   - assets/icon/Hlabu.png
   - assets/icon/Hlarbu.png
   - assets/icon/Hplum.png
   - assets/icon/Huda.png
   - assets/icon/google.png
   - assets/icon/apelclip.png
   - assets/icon/hujan.png
   - assets/icon/ketinggian.png
   - assets/icon/matahari.png
   - assets/icon/suhu.png
   - assets/icon/tanah.png
   - assets/icon/kalkulator.png
   - assets/icon/pakar.png
   - assets/text/embunTepung.txt

#  fonts:
#   - family:  MyFlutterApp
#     fonts:
#      - asset: assets/font/MyFlutterApp.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
